# Generated by Django 4.2.7 on 2026-05-27 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_alter_alimento_options_alter_categoriaanimal_options_and_more'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacompra',
            name='tipo_compra',
            field=models.CharField(choices=[('MEDICAMENTO', 'Medicamento'), ('ALIMENTO', 'Alimento'), ('ANIMAL', 'Animal'), ('OTRO', 'Otro')], default='MEDICAMENTO', max_length=30),
        ),
        migrations.CreateModel(
            name='DetalleCompraAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_arete', models.CharField(help_text='Arete del animal comprado', max_length=100)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('sexo', models.CharField(choices=[('MACHO', 'Macho'), ('HEMBRA', 'Hembra')], max_length=20)),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.categoriaanimal')),
                ('nota_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_animales', to='compras.notacompra')),
                ('raza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.raza')),
            ],
            options={
                'verbose_name': 'Detalle compra animal',
                'verbose_name_plural': 'Detalles compra animales',
            },
        ),
    ]
