# Generated by Django 4.2.7 on 2026-06-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rol_activo_rol_permisos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='rol',
            name='permisos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de claves de permisos asignados al rol'),
        ),
    ]
