# Generated by Django 4.2.7 on 2026-06-09 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fincas', '0002_transferencia_finca'),
        ('accounts', '0003_alter_rol_options_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='finca',
            field=models.ForeignKey(blank=True, help_text='Finca activa actual del usuario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='fincas.finca'),
        ),
        migrations.CreateModel(
            name='UsuarioFinca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_en_finca', models.CharField(choices=[('PROPIETARIO', 'Propietario'), ('ADMINISTRADOR', 'Administrador'), ('ENCARGADO', 'Encargado'), ('VETERINARIO', 'Veterinario'), ('LECTURA', 'Solo lectura')], default='ENCARGADO', max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_usuario', to='fincas.finca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_finca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso usuario-finca',
                'verbose_name_plural': 'Accesos usuario-finca',
                'indexes': [models.Index(fields=['usuario', 'activo'], name='uf_usuario_activo_idx'), models.Index(fields=['finca', 'activo'], name='uf_finca_activo_idx')],
                'unique_together': {('usuario', 'finca')},
            },
        ),
    ]
