# Generated by Django 4.2.7 on 2026-06-09 20:26
# Data migration: por cada usuario con finca activa, crear su acceso UsuarioFinca.

from django.db import migrations


def seed_accesos(apps, schema_editor):
    Usuario = apps.get_model('accounts', 'Usuario')
    UsuarioFinca = apps.get_model('accounts', 'UsuarioFinca')

    for usuario in Usuario.objects.filter(finca__isnull=False).iterator():
        UsuarioFinca.objects.get_or_create(
            usuario_id=usuario.id,
            finca_id=usuario.finca_id,
            defaults={'rol_en_finca': 'PROPIETARIO', 'activo': True},
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usuario_finca_usuariofinca'),
    ]

    operations = [
        migrations.RunPython(seed_accesos, noop),
    ]
