# Generated by Django 4.2.7 on 2026-06-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='contrato',
            field=models.FileField(blank=True, null=True, upload_to='empleados/contratos/'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='documento_ci',
            field=models.FileField(blank=True, null=True, upload_to='empleados/documentos/'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado_laboral',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('LICENCIA', 'Licencia'), ('SUSPENDIDO', 'Suspendido'), ('RETIRADO', 'Retirado')], default='ACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='motivo_salida',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_empleado',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('VAQUERO', 'Vaquero'), ('VETERINARIO', 'Veterinario'), ('ORDENADOR', 'Ordeñador'), ('ENCARGADO_COMPRAS', 'Encargado de Compras'), ('ENCARGADO_SANIDAD', 'Encargado de Sanidad'), ('ENCARGADO_PRODUCCION', 'Encargado de Producción'), ('OTRO', 'Otro')], default='OTRO', help_text='Rol operativo del empleado dentro de la finca.', max_length=30),
        ),
    ]
