# Generated by Django 4.2.7 on 2026-06-07 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0007_transferencia_finca'),
        ('fincas', '0002_transferencia_finca'),
        ('comercio', '0002_add_robo_to_tipo_baja_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='costo_estimado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de adquisición del animal', max_digits=12),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='modalidad',
            field=models.CharField(choices=[('POR_KILO', 'Por Kilo'), ('POR_CABEZA', 'Por Cabeza')], default='POR_KILO', max_length=20),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='utilidad',
            field=models.DecimalField(decimal_places=2, default=0, help_text='sub_total - costo_estimado', max_digits=12),
        ),
        migrations.AddField(
            model_name='muertebaja',
            name='motivo_descarte',
            field=models.CharField(blank=True, choices=[('EDAD_AVANZADA', 'Edad avanzada'), ('BAJA_PRODUCCION', 'Baja producción'), ('PROBLEMAS_REPRODUCTIVOS', 'Problemas reproductivos'), ('ENFERMEDAD_CRONICA', 'Enfermedad crónica'), ('LESION_PERMANENTE', 'Lesión permanente'), ('MAL_CARACTER', 'Mal carácter'), ('DECISION_ECONOMICA', 'Decisión económica'), ('OTRO', 'Otro')], help_text='Solo aplica cuando tipo=DESCARTE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notaventa',
            name='modalidad_venta',
            field=models.CharField(choices=[('POR_KILO', 'Por Kilo'), ('POR_CABEZA', 'Por Cabeza'), ('MIXTO', 'Mixto')], default='POR_KILO', max_length=20),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Precio por kilo o precio por cabeza según modalidad', max_digits=10),
        ),
        migrations.CreateModel(
            name='CorrallVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Corral A, Lote Norte', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_formacion', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrales_venta', to='fincas.finca')),
            ],
            options={
                'verbose_name': 'Corral de Venta',
                'verbose_name_plural': 'Corrales de Venta',
                'ordering': ['-fecha_formacion'],
            },
        ),
        migrations.AddField(
            model_name='notaventa',
            name='corral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='comercio.corrallventa'),
        ),
        migrations.CreateModel(
            name='AnimalCorral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_ingreso', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrales', to='animales.animal')),
                ('corral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animales', to='comercio.corrallventa')),
            ],
            options={
                'verbose_name': 'Animal en Corral',
                'verbose_name_plural': 'Animales en Corral',
                'unique_together': {('corral', 'animal')},
            },
        ),
    ]
