# Generated by Django 4.2.7 on 2026-06-09 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0007_transferencia_finca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='accion_recomendada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LEIDA', 'Leída'), ('EN_PROCESO', 'En proceso'), ('RESUELTA', 'Resuelta'), ('DESCARTADA', 'Descartada')], default='PENDIENTE', max_length=12),
        ),
        migrations.AddField(
            model_name='alerta',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='modulo_origen',
            field=models.CharField(choices=[('SANIDAD', 'Sanidad'), ('REPRODUCCION', 'Reproducción'), ('PRODUCCION', 'Producción'), ('FINCAS', 'Fincas'), ('PARCELAS', 'Parcelas'), ('COMERCIO', 'Comercio'), ('CATALOGOS', 'Catálogos'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=15),
        ),
        migrations.AddField(
            model_name='alerta',
            name='observacion_resolucion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10),
        ),
        migrations.AddField(
            model_name='alerta',
            name='resuelta_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gasto',
            name='centro_costo',
            field=models.CharField(blank=True, choices=[('SANIDAD', 'Sanidad'), ('REPRODUCCION', 'Reproducción'), ('ALIMENTACION', 'Alimentación'), ('MANO_DE_OBRA', 'Mano de obra'), ('PARCELA', 'Parcela'), ('FINCA', 'Finca'), ('COMERCIO', 'Comercio'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='comprobante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('CREDITO', 'Crédito'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='parcela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='animales.parcela'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='proveedor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('VACUNA_PROXIMA', 'Vacuna próxima'), ('VACUNA_VENCIDA', 'Vacuna vencida'), ('PARTO_PROXIMO', 'Parto próximo'), ('STOCK_BAJO_MEDICAMENTO', 'Stock bajo de medicamento'), ('STOCK_BAJO_ALIMENTO', 'Stock bajo de alimento'), ('PESAJE_PENDIENTE', 'Pesaje pendiente'), ('TRANSFERENCIA_PENDIENTE', 'Transferencia pendiente'), ('OTRO', 'Otro')], max_length=50),
        ),
    ]
