# Generated by Django 4.2.7 on 2026-06-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_alerta_accion_recomendada_alerta_asignado_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('VACUNA_PROXIMA', 'Vacuna próxima'), ('VACUNA_VENCIDA', 'Vacuna vencida'), ('PARTO_PROXIMO', 'Parto próximo'), ('STOCK_BAJO_MEDICAMENTO', 'Stock bajo de medicamento'), ('STOCK_BAJO_ALIMENTO', 'Stock bajo de alimento'), ('STOCK_BAJO_VACUNA', 'Stock bajo de vacuna'), ('PESAJE_PENDIENTE', 'Pesaje pendiente'), ('TRANSFERENCIA_PENDIENTE', 'Transferencia pendiente'), ('OTRO', 'Otro')], max_length=50),
        ),
    ]
