# Generated by Django 4.2.7 on 2026-06-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0004_alter_alerta_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('VACUNA_PROXIMA', 'Vacuna próxima'), ('VACUNA_VENCIDA', 'Vacuna vencida'), ('PARTO_PROXIMO', 'Parto próximo'), ('STOCK_BAJO_MEDICAMENTO', 'Stock bajo de medicamento'), ('STOCK_BAJO_ALIMENTO', 'Stock bajo de alimento'), ('STOCK_BAJO_VACUNA', 'Stock bajo de vacuna'), ('PESAJE_PENDIENTE', 'Pesaje pendiente'), ('TRANSFERENCIA_PENDIENTE', 'Transferencia pendiente'), ('TRANSFERENCIA_RECIBIDA', 'Transferencia recibida'), ('ANIMAL_SIN_PESAJE', 'Animal sin pesaje'), ('PERDIDA_PESO', 'Pérdida de peso'), ('ANIMAL_LISTO_VENTA', 'Animal listo para venta'), ('BAJA_PRODUCCION_LECHE', 'Baja producción de leche'), ('VACA_A_SECAR', 'Vaca a secar'), ('OTRO', 'Otro')], max_length=50),
        ),
    ]
