# Generated by Django 5.2.15 on 2026-06-10 16:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(default='GanadoSoft', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sistema/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='sistema/favicons/')),
                ('tema', models.CharField(choices=[('CLARO', 'Claro'), ('OSCURO', 'Oscuro')], default='CLARO', max_length=10)),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('pt', 'Português')], default='es', max_length=5)),
                ('moneda', models.CharField(default='Gs.', max_length=10)),
                ('simbolo_moneda', models.CharField(default='₲', max_length=5)),
                ('formato_fecha', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('intentos_login', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('tiempo_bloqueo_min', models.IntegerField(default=30, help_text='Minutos que se bloquea la cuenta')),
                ('jwt_expiration_horas', models.IntegerField(default=8, help_text='Horas hasta que expira el token de acceso')),
                ('jwt_refresh_expiration_dias', models.IntegerField(default=7, help_text='Días hasta que expira el token de refresco')),
                ('requerir_2fa', models.BooleanField(default=False)),
                ('complejidad_contrasena', models.CharField(choices=[('BAJA', 'Baja - 6 caracteres'), ('MEDIA', 'Media - 8 caracteres, mayúscula, número'), ('ALTA', 'Alta - 10 caracteres, mayúscula, minúscula, número, símbolo')], default='MEDIA', max_length=10)),
                ('caducidad_contrasena_dias', models.IntegerField(default=90)),
                ('registro_acciones', models.BooleanField(default=True)),
                ('email_smtp_host', models.CharField(blank=True, max_length=200, null=True)),
                ('email_smtp_port', models.IntegerField(default=587)),
                ('email_smtp_user', models.CharField(blank=True, max_length=200, null=True)),
                ('email_smtp_password', models.CharField(blank=True, max_length=200, null=True)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_from', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo_reportes', models.ImageField(blank=True, null=True, upload_to='sistema/reportes/')),
                ('pie_pagina_reportes', models.CharField(blank=True, max_length=500, null=True)),
                ('formato_por_defecto', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel')], default='PDF', max_length=10)),
                ('max_registros_reporte', models.IntegerField(default=1000)),
                ('backup_automatico', models.BooleanField(default=False)),
                ('frecuencia_backup', models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], default='SEMANAL', max_length=10)),
                ('hora_backup', models.TimeField(blank=True, null=True)),
                ('retencion_backup_dias', models.IntegerField(default=30)),
                ('ubicacion_backup', models.CharField(blank=True, max_length=500, null=True)),
                ('modulo_sanidad', models.BooleanField(default=True)),
                ('modulo_reproduccion', models.BooleanField(default=True)),
                ('modulo_produccion', models.BooleanField(default=True)),
                ('modulo_rrhh', models.BooleanField(default=True)),
                ('modulo_compras', models.BooleanField(default=True)),
                ('modulo_ventas', models.BooleanField(default=True)),
                ('modulo_alertas', models.BooleanField(default=True)),
                ('modulo_proveedores', models.BooleanField(default=True)),
                ('modulo_clientes', models.BooleanField(default=True)),
                ('modulo_bajas', models.BooleanField(default=True)),
                ('dias_gestacion', models.IntegerField(default=283, help_text='Días de gestación bovina')),
                ('dias_lactancia', models.IntegerField(default=305, help_text='Duración promedio de lactancia')),
                ('edad_destete_dias', models.IntegerField(default=210)),
                ('peso_min_destete_kg', models.DecimalField(decimal_places=2, default=180, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FAILED', 'Inicio de sesión fallido'), ('EXPORT', 'Exportación'), ('IMPORT', 'Importación')], max_length=20)),
                ('modulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Actividad',
                'verbose_name_plural': 'Logs de Actividades',
                'ordering': ['-created_at'],
            },
        ),
    ]
