# Generated by Django 4.2.7 on 2026-06-05 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0006_mejorar_vacuna_medicamento_categoria_reproductor'),
        ('fincas', '0001_initial'),
        ('catalogos', '0003_alter_alimento_options_alter_categoriaanimal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaanimal',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Categoría Animal', 'verbose_name_plural': 'Categorías Animales'},
        ),
        migrations.AddField(
            model_name='categoriaanimal',
            name='edad_max_meses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriaanimal',
            name='edad_min_meses',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='categoriaanimal',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categoriaanimal',
            name='permite_lactancia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoriaanimal',
            name='permite_reproduccion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoriaanimal',
            name='peso_max_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='categoriaanimal',
            name='peso_min_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='categoriaanimal',
            name='sexo_aplica',
            field=models.CharField(choices=[('MACHO', 'Macho'), ('HEMBRA', 'Hembra'), ('AMBOS', 'Ambos')], default='AMBOS', max_length=10),
        ),
        migrations.AddField(
            model_name='categoriaanimal',
            name='tipo_produccion',
            field=models.CharField(choices=[('CARNE', 'Carne'), ('LECHE', 'Leche'), ('DOBLE_PROPOSITO', 'Doble propósito'), ('TODOS', 'Todos')], default='TODOS', max_length=20),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='dias_retiro_carne',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='dias_retiro_leche',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='dosis_recomendada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='presentacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='principio_activo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='via_aplicacion',
            field=models.CharField(blank=True, choices=[('INTRAMUSCULAR', 'Intramuscular'), ('SUBCUTANEA', 'Subcutánea'), ('INTRADERMICA', 'Intradérmica'), ('ORAL', 'Oral'), ('TOPICA', 'Tópica'), ('INTRAVENOSA', 'Intravenosa')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reproductor',
            name='animal_interno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='como_reproductor', to='animales.animal'),
        ),
        migrations.AddField(
            model_name='reproductor',
            name='costo_pajuela',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reproductor',
            name='facilidad_parto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Puntaje de facilidad de parto (1-10)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='reproductor',
            name='stock_pajuelas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reproductor',
            name='tipo_reproductor',
            field=models.CharField(blank=True, choices=[('TORO', 'Toro'), ('SEMEN_CONVENCIONAL', 'Semen Convencional'), ('SEMEN_SEXADO', 'Semen Sexado')], default='TORO', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reproductor',
            name='valor_genetico',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DEP o valor genético estimado', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='enfermedad_previene',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='lote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='stock_cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='vacuna',
            unique_together={('finca', 'nombre')},
        ),
    ]
