# Generated by Django 4.2.7 on 2026-06-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_mejorar_alimento_veterinario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaanimal',
            name='permite_reproduccion',
            field=models.BooleanField(default=False),
        ),
    ]
