# Generated by Django 5.2.15 on 2026-06-08 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0007_transferencia_finca'),
        ('fincas', '0002_transferencia_finca'),
        ('sanidad', '0003_desparasitacion_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('categoria', models.CharField(choices=[('INFECCIOSA', 'Infecciosa'), ('PARASITARIA', 'Parasitaria'), ('METABOLICA', 'Metabólica'), ('REPRODUCTIVA', 'Reproductiva'), ('RESPIRATORIA', 'Respiratoria'), ('DIGESTIVA', 'Digestiva'), ('OTRA', 'Otra')], default='OTRA', max_length=20)),
                ('sintomas', models.TextField()),
                ('causa', models.TextField(blank=True, null=True)),
                ('tratamiento_recomendado', models.TextField(blank=True, null=True)),
                ('tiempo_recuperacion_dias', models.IntegerField(default=0)),
                ('es_zoonotica', models.BooleanField(default=False)),
                ('mortalidad_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enfermedad',
                'verbose_name_plural': 'Enfermedades',
                'db_table': 'sanidad_enfermedad',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='vacunacion',
            name='campana',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vacunacion',
            name='dosis_aplicada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacunacion',
            name='fecha_proxima',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='enfermedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos', to='sanidad.enfermedad'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='enfermedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamientos', to='sanidad.enfermedad'),
        ),
        migrations.CreateModel(
            name='ExamenLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(choices=[('SANGRE', 'Análisis de Sangre'), ('HECES', 'Examen de Heces'), ('LECHE', 'Análisis de Leche'), ('ORINA', 'Análisis de Orina'), ('BIOPSIA', 'Biopsia'), ('CULTIVO', 'Cultivo Bacteriano'), ('PCR', 'PCR'), ('OTRO', 'Otro')], max_length=20)),
                ('laboratorio', models.CharField(max_length=200)),
                ('fecha_toma', models.DateField()),
                ('fecha_resultado', models.DateField(blank=True, null=True)),
                ('resultado', models.TextField()),
                ('es_normal', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='examenes_laboratorio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_laboratorio', to='animales.animal')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_laboratorio', to='fincas.finca')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Examen de Laboratorio',
                'verbose_name_plural': 'Exámenes de Laboratorio',
                'db_table': 'sanidad_examen_laboratorio',
                'ordering': ['-fecha_toma'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMastitis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cuarto_afectado', models.CharField(choices=[('DI', 'Derecho Izquierdo'), ('DD', 'Derecho Derecho'), ('TI', 'Trasero Izquierdo'), ('TD', 'Trasero Derecho'), ('MULTIPLE', 'Múltiples')], max_length=10)),
                ('tipo', models.CharField(choices=[('CLINICA', 'Clínica'), ('SUBCLINICA', 'Subclínica'), ('CRONICA', 'Crónica')], max_length=20)),
                ('bacteria', models.CharField(blank=True, max_length=150, null=True)),
                ('recuento_cels_somaticas', models.IntegerField(blank=True, null=True)),
                ('se_curo', models.BooleanField(default=False)),
                ('fecha_curacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastitis_registros', to='animales.animal')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastitis_registros', to='fincas.finca')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mastitis_registrados', to=settings.AUTH_USER_MODEL)),
                ('tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mastitis_casos', to='sanidad.tratamiento')),
            ],
            options={
                'verbose_name': 'Registro de Mastitis',
                'verbose_name_plural': 'Registros de Mastitis',
                'db_table': 'sanidad_registro_mastitis',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TiempoRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_retiro', models.CharField(choices=[('CARNE', 'Retiro de Carne'), ('LECHE', 'Retiro de Leche'), ('AMBOS', 'Ambos')], max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_retiro', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos_retiro', to='animales.animal')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiempos_retiro_registrados', to=settings.AUTH_USER_MODEL)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos_retiro', to='sanidad.tratamiento')),
            ],
            options={
                'verbose_name': 'Tiempo de Retiro',
                'verbose_name_plural': 'Tiempos de Retiro',
                'db_table': 'sanidad_tiempo_retiro',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
