# Generated by Django 4.2.7 on 2026-06-23 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fincas', '0004_map_transfer_estados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionGanadera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_original', models.FileField(upload_to='importaciones/%Y/%m/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('CARGADO', 'Cargado'), ('VALIDANDO', 'Validando'), ('LISTO', 'Listo para importar'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('COMPLETADO_CON_ERRORES', 'Completado con errores'), ('FALLIDO', 'Fallido'), ('CANCELADO', 'Cancelado')], default='CARGADO', max_length=30)),
                ('modo', models.CharField(choices=[('SOLO_CREAR', 'Solo crear nuevos'), ('ACTUALIZAR_EXISTENTES', 'Actualizar existentes'), ('CREAR_O_ACTUALIZAR', 'Crear o actualizar')], default='SOLO_CREAR', max_length=30)),
                ('modo_estricto', models.BooleanField(default=True)),
                ('total_filas', models.IntegerField(default=0)),
                ('filas_validas', models.IntegerField(default=0)),
                ('creados', models.IntegerField(default=0)),
                ('actualizados', models.IntegerField(default=0)),
                ('omitidos', models.IntegerField(default=0)),
                ('total_errores', models.IntegerField(default=0)),
                ('resumen_json', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importaciones', to='fincas.finca')),
            ],
            options={
                'verbose_name': 'Importación ganadera',
                'verbose_name_plural': 'Importaciones ganaderas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImportacionGanaderaError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoja', models.CharField(max_length=50)),
                ('numero_fila', models.IntegerField()),
                ('campo', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.TextField(blank=True, null=True)),
                ('codigo_error', models.CharField(max_length=60)),
                ('mensaje', models.TextField()),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errores', to='importaciones.importacionganadera')),
            ],
            options={
                'verbose_name': 'Error de importación',
                'verbose_name_plural': 'Errores de importación',
                'ordering': ['hoja', 'numero_fila'],
                'indexes': [models.Index(fields=['importacion', 'numero_fila'], name='imperr_imp_fila_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='importacionganadera',
            index=models.Index(fields=['finca', 'fecha_creacion'], name='imp_finca_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='importacionganadera',
            index=models.Index(fields=['estado'], name='imp_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='importacionganadera',
            index=models.Index(fields=['creado_por'], name='imp_creado_por_idx'),
        ),
    ]
