# Generated by Django 4.2.7 on 2026-06-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacionganadera',
            name='crear_categorias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importacionganadera',
            name='crear_parcelas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importacionganadera',
            name='crear_razas',
            field=models.BooleanField(default=False),
        ),
    ]
