# Generated by Django 4.2.7 on 2026-06-09 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0007_transferencia_finca'),
        ('fincas', '0002_transferencia_finca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngordeAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('peso_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peso_objetivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo_engorde', models.CharField(choices=[('INTENSIVO', 'Intensivo'), ('EXTENSIVO', 'Extensivo'), ('SEMI_INTENSIVO', 'Semi-intensivo')], default='SEMI_INTENSIVO', max_length=20)),
                ('lote_grupo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('EN_ENGORDE', 'En engorde'), ('LISTO_VENTA', 'Listo para venta'), ('RETIRADO', 'Retirado'), ('VENDIDO', 'Vendido')], default='EN_ENGORDE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engordes', to='animales.animal')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engordes', to='fincas.finca')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engordes_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Engorde de animal',
                'verbose_name_plural': 'Engordes de animales',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['finca', 'estado'], name='eng_finca_estado_idx'), models.Index(fields=['animal', 'estado'], name='eng_animal_estado_idx')],
            },
        ),
    ]
