# Generated by Django 4.2.7 on 2026-06-06 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animales', '0007_transferencia_finca'),
        ('fincas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaFinca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transferencia', models.DateField()),
                ('motivo', models.CharField(choices=[('CAMBIO_FINCA', 'Cambio de finca'), ('ROTACION_GENERAL', 'Rotación general'), ('COMPRA_INTERNA', 'Compra interna'), ('REUBICACION', 'Reubicación'), ('MANEJO_SANITARIO', 'Manejo sanitario'), ('MANEJO_REPRODUCTIVO', 'Manejo reproductivo'), ('OTRO', 'Otro')], default='CAMBIO_FINCA', max_length=30)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('finca_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_entrada', to='fincas.finca')),
                ('finca_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_salida', to='fincas.finca')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='DetalleTransferenciaFinca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_animal_antes', models.CharField(default='ACTIVO', max_length=30)),
                ('estado_animal_despues', models.CharField(default='ACTIVO', max_length=30)),
                ('peso_actual_transferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('recibido', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_detalle', to='animales.animal')),
                ('parcela_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_transferencia_entrada', to='animales.parcela')),
                ('parcela_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_transferencia_salida', to='animales.parcela')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='fincas.transferenciafinca')),
            ],
        ),
        migrations.AddIndex(
            model_name='transferenciafinca',
            index=models.Index(fields=['finca_origen', 'estado'], name='tf_origen_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='transferenciafinca',
            index=models.Index(fields=['finca_destino', 'estado'], name='tf_destino_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='transferenciafinca',
            index=models.Index(fields=['fecha_transferencia'], name='tf_fecha_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detalletransferenciafinca',
            unique_together={('transferencia', 'animal')},
        ),
    ]
