# Generated by Django 4.2.7 on 2026-06-09 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fincas', '0002_transferencia_finca'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciafinca',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferenciafinca',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferenciafinca',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferenciafinca',
            name='rechazado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_rechazadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferenciafinca',
            name='recibido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transferenciafinca',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_RECEPCION', 'Pendiente de recepción'), ('RECIBIDA', 'Recibida'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20),
        ),
    ]
