# Generated by Django 4.2.7 on 2026-06-05 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0003_animal_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='animal',
            new_name='animales_an_nombre_0cacaa_idx',
            old_name='animales_an_nombre_idx',
        ),
        migrations.RenameIndex(
            model_name='animal',
            new_name='animales_an_nro_are_6f29c9_idx',
            old_name='animales_an_nro_are_idx',
        ),
        migrations.RenameIndex(
            model_name='animal',
            new_name='animales_an_fecha_n_bddd04_idx',
            old_name='animales_an_fecha_n_idx',
        ),
        migrations.RenameIndex(
            model_name='animal',
            new_name='animales_an_estado_45a62a_idx',
            old_name='animales_an_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='animal',
            new_name='animales_an_finca_i_bf188a_idx',
            old_name='animales_an_finca_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='animal',
            new_name='animales_an_finca_i_5730a4_idx',
            old_name='animales_an_finca_fecha_idx',
        ),
    ]
