# Generated by Django 4.2.7 on 2026-06-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0004_rename_animales_an_nombre_idx_animales_an_nombre_0cacaa_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='animal',
            new_name='ani_finca_estado_idx',
            old_name='animales_an_finca_i_bf188a_idx',
        ),
        migrations.RenameIndex(
            model_name='animal',
            new_name='ani_finca_freg_idx',
            old_name='animales_an_finca_i_5730a4_idx',
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['fecha_ingreso'], name='animales_an_fecha_i_a2c43e_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['fecha_registro'], name='animales_an_fecha_r_a2e9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['sexo'], name='animales_an_sexo_97d43e_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['tipo_produccion'], name='animales_an_tipo_pr_9cc468_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['origen'], name='animales_an_origen_4cc92d_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['finca', 'fecha_nacimiento'], name='ani_finca_fnac_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['finca', 'fecha_ingreso'], name='ani_finca_fing_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['finca', 'sexo'], name='ani_finca_sexo_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['finca', 'tipo_produccion'], name='ani_finca_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['finca', 'origen'], name='ani_finca_origen_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['finca', 'raza', 'categoria'], name='ani_finca_raza_cat_idx'),
        ),
    ]
