# Generated by Django 4.2.7 on 2026-06-05 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fincas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animales', '0005_rename_animales_an_finca_i_bf188a_idx_ani_finca_estado_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateField()),
                ('motivo', models.CharField(blank=True, choices=[('ROTACION', 'Rotación de potrero'), ('SANIDAD', 'Razones sanitarias'), ('ALIMENTACION', 'Manejo de alimentación'), ('SEPARACION', 'Separación por gestación/cría'), ('VENTA', 'Preparación para venta'), ('MANTENIMIENTO', 'Mantenimiento de parcela'), ('OTRO', 'Otro')], max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_movimiento', '-fecha_registro'],
            },
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['finca', 'peso'], name='ani_finca_peso_idx'),
        ),
        migrations.AddIndex(
            model_name='animalparcela',
            index=models.Index(fields=['animal', 'fecha_salida'], name='ap_animal_salida_idx'),
        ),
        migrations.AddIndex(
            model_name='animalparcela',
            index=models.Index(fields=['parcela', 'fecha_salida'], name='ap_parcela_salida_idx'),
        ),
        migrations.AddIndex(
            model_name='parcela',
            index=models.Index(fields=['finca'], name='par_finca_idx'),
        ),
        migrations.AddIndex(
            model_name='parcela',
            index=models.Index(fields=['finca', 'estado'], name='par_finca_estado_idx'),
        ),
        migrations.AddField(
            model_name='movimientoanimal',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='animales.animal'),
        ),
        migrations.AddField(
            model_name='movimientoanimal',
            name='finca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_animales', to='fincas.finca'),
        ),
        migrations.AddField(
            model_name='movimientoanimal',
            name='parcela_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_animales', to='animales.parcela'),
        ),
        migrations.AddField(
            model_name='movimientoanimal',
            name='parcela_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_animales', to='animales.parcela'),
        ),
        migrations.AddField(
            model_name='movimientoanimal',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='movimientoanimal',
            index=models.Index(fields=['animal', 'fecha_movimiento'], name='mov_animal_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoanimal',
            index=models.Index(fields=['finca', 'fecha_movimiento'], name='mov_finca_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoanimal',
            index=models.Index(fields=['parcela_origen'], name='mov_origen_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoanimal',
            index=models.Index(fields=['parcela_destino'], name='mov_destino_idx'),
        ),
    ]
