# Generated by Django 4.2.7 on 2026-06-06 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fincas', '0001_initial'),
        ('animales', '0006_mejorar_vacuna_medicamento_categoria_reproductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoanimal',
            name='finca_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_recibidos', to='fincas.finca'),
        ),
        migrations.AlterField(
            model_name='movimientoanimal',
            name='motivo',
            field=models.CharField(blank=True, choices=[('ROTACION', 'Rotación de potrero'), ('SANIDAD', 'Razones sanitarias'), ('ALIMENTACION', 'Manejo de alimentación'), ('SEPARACION', 'Separación por gestación/cría'), ('VENTA', 'Preparación para venta'), ('MANTENIMIENTO', 'Mantenimiento de parcela'), ('TRANSFERENCIA_FINCA', 'Transferencia entre fincas'), ('OTRO', 'Otro')], max_length=100, null=True),
        ),
    ]
