# Generated by Django 5.2.15 on 2026-06-07 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0007_transferencia_finca'),
        ('catalogos', '0007_alter_categoriaanimal_permite_reproduccion'),
        ('fincas', '0002_transferencia_finca'),
        ('reproduccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbortoDetallado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa', models.CharField(choices=[('INFECCIOSO', 'Infeccioso (Brucelosis, Leptospira, etc.)'), ('TOXICO', 'Tóxico (Plantas, Micotoxinas)'), ('NUTRICIONAL', 'Nutricional (Deficiencias)'), ('TRAUMATICO', 'Traumático'), ('GENETICO', 'Genético'), ('HORMONAL', 'Hormonal'), ('ESTRES', 'Estrés'), ('DESCONOCIDO', 'Desconocido')], max_length=20)),
                ('descripcion', models.TextField()),
                ('estado_feto', models.CharField(blank=True, choices=[('MUMMIFIED', 'Momificado'), ('MACERADO', 'Macerado'), ('FRESCO', 'Fresco'), ('AUTOLIZADO', 'Autolizado')], max_length=20, null=True)),
                ('semanas_gestacion', models.PositiveIntegerField(help_text='Semanas de gestación al abortar')),
                ('tratamiento_aplicado', models.TextField(blank=True)),
                ('medidas_preventivas', models.TextField(blank=True)),
                ('costo_asociado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reproduccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aborto_detalle', to='reproduccion.reproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='Celo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('NATURAL', 'Celo Natural'), ('INDUCIDO', 'Celo Inducido'), ('SINCRONIZADO', 'Celo Sincronizado')], default='NATURAL', max_length=20)),
                ('intensidad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=20)),
                ('detectado_por', models.CharField(blank=True, max_length=150)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celos', to='fincas.finca')),
                ('hembra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celos', to='animales.animal')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Destete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_destete', models.DateField()),
                ('tipo', models.CharField(choices=[('NATURAL', 'Natural'), ('PRECOZ', 'Precoz'), ('FORZADO', 'Forzado')], default='NATURAL', max_length=20)),
                ('edad_destete_dias', models.PositiveIntegerField(help_text='Edad de la cría en días')),
                ('peso_cria', models.DecimalField(blank=True, decimal_places=2, help_text='Peso al destete (kg)', max_digits=8, null=True)),
                ('estado_cria', models.CharField(blank=True, help_text='Buena, Regular, Mala', max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destete_recibido', to='animales.animal')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destetes', to='fincas.finca')),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destetes_como_madre', to='animales.animal')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HembraRepetidora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_servicios', models.PositiveIntegerField(default=0, help_text='Número de servicios sin preñez')),
                ('fecha_ultimo_servicio', models.DateField(blank=True, null=True)),
                ('servicios_fallidos', models.JSONField(blank=True, default=list, help_text='Lista de fechas de servicios fallidos')),
                ('evaluada_veterinario', models.BooleanField(default=False)),
                ('causa_presunta', models.TextField(blank=True)),
                ('descartada', models.BooleanField(default=False)),
                ('fecha_descarte', models.DateField(blank=True, null=True)),
                ('motivo_descarte', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repetidora', to='animales.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Palpacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('resultado', models.CharField(choices=[('POSITIVO', 'Positivo (Preñada)'), ('NEGATIVO', 'Negativo (Vacía)'), ('SOSPECHOSO', 'Sospechoso'), ('QUISTE', 'Quiste')], max_length=20)),
                ('dias_gestacion_estimados', models.PositiveIntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palpaciones', to='fincas.finca')),
                ('hembra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palpaciones', to='animales.animal')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.veterinario')),
            ],
        ),
    ]
